### ISSUE TITLE
fwrite(): send of 6 bytes failed with errno=32 Broken pipe

### ISSUE THREAD

**Issue by ankurAuriga** [magepal/magento2-gmail-smtp-app#100]
All of sudden I am start getting this error on production server.

fwrite(): send of 6 bytes failed with errno=32 Broken pipe in vendor/magento/zendframework1/library/Zend/Mail/Protocol/Abstract.php on line 324

**Comment by srenon** [comment]
Since it was working before, I would double check with my hosting company to see if they made any server changes.

Take a look at https://stackoverflow.com/questions/13694351/error-while-sending-an-email-with-codeigniter and https://forum.codeigniter.com/thread-64863.html
