### ISSUE TITLE
order emails dont send

### ISSUE THREAD

**Issue by woakley** [magepal/magento2-gmail-smtp-app#102]
Test emails work great (x2)
Other store emails work great

Only the initial order email doesn't get sent either to the customer or to the store owner.

System log:
main.ERROR: 5.5.4 Syntax: RCPT To:<address>
 [] []

Magento 2.2.3
PHP 7.0.28

**Comment by srenon** [comment]
Did you try disabling and see if order email works?

**Comment by woakley** [comment]
Hi, yes I can confirm that when disabled the order email sends and there is no error recorded in the system log.

**Comment by Sharpy310** [comment]
Try this fix, worked for me for a very similar issue: https://github.com/sashas777/bug-from-email
