### ISSUE TITLE
Error message on email send and only 1 test email

### ISSUE THREAD

**Issue by MartinaEL** [magepal/magento2-gmail-smtp-app#105]
I am getting the following error on the front end of my Magento 2 website  when trying to share Wishlists or send a Contact Form and when I send the SMTP test email. I do receive one of the two test emails though - just not the second;

Warning: stream_socket_enable_crypto(): Peer certificate CN='xxx.au' did not match expected CN=`localhost' in public_html/vendor/magento/zendframework1/library/Zend/Mail/Protocol/Smtp.php on line 206

#### PHP Version: 7

**Comment by srenon** [comment]
Your SSL cert seems to not be valid.

Take a look at https://stackoverflow.com/questions/30371910/phpmailer-generates-php-warning-stream-socket-enable-crypto-peer-certificate

**Comment by srenon** [comment]
This is a server config issue and not an extension issue. You are more than welcome to open paid support and we will try to fix it.

**Comment by dev-Dhaval** [comment]
Its will showing wrong email address in FROM. It's not use magento system -> configuration mail id for FROM address.
