### ISSUE TITLE
Username and password not accepted but correct

### ISSUE THREAD

**Issue by Axeldekker** [magepal/magento2-gmail-smtp-app#106]
#### Magento version #: 
2.2.1

#### Edition (EE, CE, OS, etc): 
CE

#### Expected behavior: 
Sending out a correct test email without error

#### Actual behavior: 
Pop up message with: 5.7.8 Username and Password not accepted. Learn more at - 5.7.8 https://support.google.com/mail/?p=BadCredentials z55sm449823qth.11 - gsmtp

#### Steps to reproduce: 
Sending out the test email in the backend of the application.

#### Preconditions

Digital Ocean Droplet Ubuntu 14.04.4 LTS (GNU/Linux 4.4.0-31-generic x86_64)

**Comment by srenon** [comment]
Did you follow the instruction at https://support.google.com/mail/?p=BadCredentials  ?
