### ISSUE TITLE
There are no  command in setup namespace

### ISSUE THREAD

**Issue by Mohd-Hasan** [magepal/magento2-gmail-smtp-app#107]
#### Edition (EE, CE, OS, etc): Open source

Hello guys, i using magento 2.1.3 and trying to install magento2-gmail-smtp-app but when i try to run 

`php -f bin/magento setup:upgrade`
It returns me _**There are no command in setup namespace**_

**Comment by srenon** [comment]
@Mohd-Hasan ... This is an environment issue ... see https://magento.stackexchange.com/questions/103774/magento-2-there-are-no-commands-defined-in-the-setup-namespace-on-windows
