### ISSUE TITLE
Not working on PHP7.2

### ISSUE THREAD

**Issue by zikezhang** [magepal/magento2-gmail-smtp-app#111]
#### Magento version #: 
2.2.6

#### Edition (EE, CE, OS, etc):
CE , Ubuntu 16

#### Actual behavior:
Package magepal/magento2-gmailsmtpapp at version  has a PHP requirement incompatible with your PHP version (7.2.5)

#### Steps to reproduce:
run composer require magepal/magento2-gmailsmtpapp to install it.

**Comment by srenon** [comment]
Composer should not install because of https://github.com/magepal/magento2-gmail-smtp-app/blob/master/composer.json#L16

Does Magento support PHP 7.2?

https://github.com/magento/magento2/issues/12273

https://devdocs.magento.com/guides/v2.2/install-gde/system-requirements-tech.html
