### ISSUE TITLE
Recent password change has stopped emails from sending.

### ISSUE THREAD

**Issue by Dan547** [magepal/magento2-gmail-smtp-app#112]
I have recently changed the gmail password of the account associated with the credentials set in Magento for SMTP.

This has stopped emails from going out; such as order emails.

I have updated the password countless times (see below)

<img width="780" alt="screen shot 2018-06-16 at 20 32 56" src="https://user-images.githubusercontent.com/8796791/41501885-aecb82d0-71a4-11e8-89ab-83eb0db3154e.png">

But with no luck, even after cleaning the cache as it suggests.

When I enter the password without 'Saving the config' the test email sends just fine.

I have also gone through and deleted the row - system/gmailsmtpapp/password from core_config_data (as seen on other posts) but is it defaulting back to a value i dont know/didnt set.

Please any help on getting the password updated and working would be very appreciated.

**Comment by srenon** [comment]
I would strongly recommend updating this module to the latest version. 

Also what version of Magento are you running?

**Comment by Dan547** [comment]
I will update the module and get back to you.

I am running Magento 2.1.9.

Thanks for your response.

**Comment by Dan547** [comment]
I can confirm updating the module has fixed the issue.

Thanks for your help 👍
