### ISSUE TITLE
Order related emails not sending but others working fine

### ISSUE THREAD

**Issue by Sharpy310** [magepal/magento2-gmail-smtp-app#113]
#### Magento version #:
Magento 2.2.4

#### Edition (EE, CE, OS, etc):
CE, running through Ubuntu 17.10 Artful Aardvark

#### Expected behavior:
Placing order through frontend, backend, shipping order, invoicing order
Expect related email to be sent to customer

#### Actual behavior:
No email received

#### Steps to reproduce:
Place order through website.

#### Preconditions
We're using our own SMTP server which is sucessfully set up, tested (2x test emails) and works fine for all other emails e.g. if a customer changes password, they are emailed, if they subscribe to newsletter, they're emailed. But any order relating to transactional email (order, comments, shipment, invoice etc) are not sent.
In an attempt to debug this issue, I added a BCC on the emails on new orders to an internal email address, which came through fine, however the "From" field is completely empty however I have set the "Set Reply-To", "Set From" and "Set Return-Path" to Yes.

Disabling the module and trying again doesn't work as we don't have Sendmail configured and use SMTP solely for emails.

All of the Store Email Addresses are configured correctly; General Contact, Sales Rep, Customer Support etc. are all set to the same email address and is the same email address as has been set up in the SMTP config.

We are running Multisite but this is being tested through the default store. Store is also in production mode.

**Comment by srenon** [comment]
I'm not able to reproduce this on a fresh 2.2.4 install.

![image](https://user-images.githubusercontent.com/1415141/41685564-cfec48c0-74ae-11e8-9c1d-7784023efa5d.png)


You are more than welcome to puchase paid support at https://www.magepal.com/magento2/support.html and we will be more than happy to fix it for you. 

Full refund if we are not able to fix it

**Comment by Sharpy310** [comment]
### *Issue resolved*

This patch appears to fix issue: https://github.com/sashas777/bug-from-email

Thanks anyway for your help.
