### ISSUE TITLE
Can't install because of Magento_Review

### ISSUE THREAD

**Issue by smoi** [magepal/magento2-gmail-smtp-app#114]
I'm installing the module using 

> php -f bin/magento module:enable --clear-static-content MagePal_GmailSmtpApp

and I've disable the Magento_Review extension and during the install of the module I get this error 

> Cannot enable MagePal_GmailSmtpApp because it depends on disabled modules:
> Magento_Review: MagePal_GmailSmtpApp->Magento_Backend->Magento_Reports->Magento_Review

Is there a way to install it without the review module?

**Comment by smoi** [comment]
even if I got that error the extension is installed in the backend. I've configured the smtp and it sends the test email but I don't receive any other email like orders, forgot password etc

**Comment by srenon** [comment]
Could you update this ticket with relevant info about your store (see new issue template by clicking on "New Issue" and fill out more info about your store)

**Comment by smoi** [comment]
here it is

#### Magento version #:
2.2.5

#### Edition (EE, CE, OS, etc):
CE

#### Expected behavior:
Order confirmed email
#### Actual behavior:
Email is not sent even if the test emails are successfully sent, also forgot password works

**Comment by srenon** [comment]
@smoi ... take a look at https://github.com/magepal/magento2-gmail-smtp-app/issues/113

**Comment by smoi** [comment]
Hi @srenon ,

thank you, i've followed [this](https://github.com/sashas777/bug-from-email/issues/2#issuecomment-401997627) and fixed Magento bug
