### ISSUE TITLE
From address empty when the plugin is enabled.

### ISSUE THREAD

**Issue by mariamghalleb** [magepal/magento2-gmail-smtp-app#116]
#### Steps to reproduce:
1. Enable your smtp module
2. Sales->Orders->Select any order->Write down a comment->Notify customer By Email->Submit Email
3.The email is sent with no "From address" (see attachement) 
![capture](https://user-images.githubusercontent.com/28814080/42104558-ef58fe52-7bc4-11e8-9a9c-b2c91b192fd2.PNG)

#### Preconditions
Php 7, Magento CE 2.2.4

PLEASE NOTE:

This occurs only when your SMTP module is enabled.

**Comment by srenon** [comment]
@mariamghalleb 

I'm not able to reproduce your issue on a fresh install of Magento 2.2.4

![image](https://user-images.githubusercontent.com/1415141/42105248-ad5261be-7b9d-11e8-89f8-c3e3095b083e.png)

**Comment by mariamghalleb** [comment]
can you please screenshot your SMTP configuration?

**Comment by palo** [comment]
Same here. 
```
  host gmail-smtp-in.l.google.com [***.***.**.**]
    SMTP error from remote mail server after pipelined end of data:
    550-5.7.1 [**.**.***.**      11] Our system has detected that this message is
    550-5.7.1 not RFC 5322 compliant:
    550-5.7.1 'From' header is missing.
```

**Comment by palo** [comment]
@mariamghalleb quick workaround if your not using multistore:

in 'vendor/magepal/magento2-gmailsmtpapp/Plugin/Mail/TransportPlugin.php'  at line 70 add
`$message->setFrom('yourshop@example.com');`

Example:
```
        if ($returnPathEmail !== null && $dataHelper->getConfigSetFrom()) {
            $message->clearFrom();
            $message->setFrom($returnPathEmail);
        }
        
        $message->setFrom('yourshop@example.com');
```
recompile, clear cache

**Comment by srenon** [comment]
@palo ... you should update to the latest version

**Comment by srenon** [comment]
@mariamghalleb @palo ... take a look at https://github.com/magepal/magento2-gmail-smtp-app/issues/113

**Comment by palo** [comment]
@srenon thanks for helping
