### ISSUE TITLE
compatible with magneto 2.2.5?  no order confirmation mail, no shipment mail 

### ISSUE THREAD

**Issue by Jacob-Wilsons** [magepal/magento2-gmail-smtp-app#117]
Is this extension compatible with magneto 2.2.5?

I have the same issue as described  [issues/16231](https://github.com/magento/magento2/issues/16231) 

Preconditions
magento 2.2.5
magento2-gmailsmtpapp

Steps to reproduce

Upgrade magento to 2.2.5
Check Stores-> Advanced -> System -> Gmail/Google Apps SMTP Pro, all configurations are ok.
Click "Send test email", can receive test mail correctly.
Can send mail when a new user is registered. 
Can send mail when password reset.
Can send mail when newsletter subscribed/ unsubscribe

After user placing an order (payment via paypal, or payment as "cash / check" method), no confirmation mail, after ship the order, no shipment mail.

I'm not sure, if this issue is related to magento2-gmailsmtpapp extension or to magento core file ?

Thanks

**Comment by srenon** [comment]
This is a core bug... take a look at https://github.com/magepal/magento2-gmail-smtp-app/issues/116 and https://github.com/magepal/magento2-gmail-smtp-app/issues/113

**Comment by Jacob-Wilsons** [comment]
@srenon tank you. I found the bug and  fixed it in TransportPlugin.php

I have a question about updating gmail-smtp-app module.
If installed via composer it is all clear. 
What is the correct way to update it if was installed manually without using composer? Thanks

**Comment by srenon** [comment]
You could either:

1. Delete folder app/code/MagePal and install using composer (all your setting should still be save in the db)

2. Download master branch at https://github.com/magepal/magento2-gmail-smtp-app/archive/master.zip and replace the content of app/code/MagePal

**Comment by Jacob-Wilsons** [comment]
Method above worked just fine.  Thank you @srenon
