### ISSUE TITLE
Permission Denied while sending a test email.

### ISSUE THREAD

**Issue by yonifine** [magepal/magento2-gmail-smtp-app#118]
Hi 

I was testing your extension on magento 2. It gives me permission denied with out giving some details. Eg. where the permission is denied either from the google SMTP side or from magento side. Attached is the screenshoot of the error and my configuration. I am using Magento 2.2.5

![capture1](https://user-images.githubusercontent.com/5861016/42409178-0cb120ae-81df-11e8-9561-038997ce29be.PNG)
![capture2](https://user-images.githubusercontent.com/5861016/42409179-0ce2b4ca-81df-11e8-85e7-236240ac726d.PNG)

**Comment by srenon** [comment]
That is not our extension
