### ISSUE TITLE
Module installed, test mail working, not sure If store mail is using SMTP

### ISSUE THREAD

**Issue by dmarkos** [magepal/magento2-gmail-smtp-app#119]
Hello, 

I had a Magento 2.2.2 setup working with default emails. I am using the store email addresses (I have two different email addresses for different notifications). 

Now I want to add SMTP support for my emails. I installed and setup you module and the test mail are both sent. Am I set, or do I need to do anything else? How about the default email settings? 
![image](https://user-images.githubusercontent.com/5176216/42995725-35e37c0c-8c1a-11e8-9436-ed17173d37c8.png)

Also, how about the fact I am using two different emails addresses (same domain though)? Could I use them both and use the SMTP server?

**Comment by srenon** [comment]
Are you trying to use 2 different SMTP email account (username/password) within the same store? if so no.

The workaround would be to create an account like  ```web@store.com```, then use the relpy-to as the different emails

**Comment by dmarkos** [comment]
Say that I want to use 1 SMTP email account (ie. web@store.com) besides setting up the module and test it, what else should be done in order to use SMTP?

Should I change the email setting (Host and port)? 

I am sending email but I am not sure if I am using SMTP or default port 25.

**Comment by dmarkos** [comment]
So, before install the SMTP module, the emails send from Magento were send to spam and there was no encryption. After installing the module, Magento mail was sent into inbox and encryption (in my case TLS) was used. Success the mails are sent via SMTP.

**Comment by srenon** [comment]
I'm not sure if I understand what you are trying to do and since this is clearly not a bug or issue within this extension; what I would recommend is for you to open a paid support so someone can take the time to understand your need and better assist you. https://www.magepal.com/magento2/extensions/custom-smtp.html

**Comment by dmarkos** [comment]
There is no need. The only confusion was with how the module worked and the mails were sent. I couldn't tell if the email was sent via SMTP or not. Confusion cleared, and SMTP working.

**Comment by srenon** [comment]
Fantastic!
