### ISSUE TITLE
2nd test email is not sending

### ISSUE THREAD

**Issue by menghao93** [magepal/magento2-gmail-smtp-app#120]
#### Preconditions
Magento version 2.2
php version 7.0
NGINX

Appreciate if you can tell me which part I should look into in order to find out the problem, because there is no error in exception, debug and system log when I try to send email. 

Thanks !

**Comment by srenon** [comment]
What version of Magento are you using 2.2.0?

After pressing the "test" button, did you get success or error message?

**Comment by menghao93** [comment]
I got a success message but I only receive 1st email.

**Comment by srenon** [comment]
I never see that issue before, did you check your junk mail?

**Comment by menghao93** [comment]
I checked my junk mail. I check exception, debug, system log, there is no trace of any error being thrown. Tried with multiple email address, no luck.
