### ISSUE TITLE
Add workaround for email issues in M2.2.4/2.2.5

### ISSUE THREAD

**Issue by srenon** [magepal/magento2-gmail-smtp-app#121]
#### Actual behavior:
Order email not sending

#### Preconditions

Review issue at https://github.com/magento/magento2/issues/14952 and add a workaround in our core module

**Comment by InternetMedicineMan** [comment]
You don't really need a work around unless the user needs the new Amazon modules active. I think it's ridiculous that Magento keeps adding new modules that break the system. I think on 2.2.3 there were two new shipping modules that broke something else.

Anyway a quick work around for the email is to just disable the Amazon modules:

php bin/magento module:disable Amazon_Core Amazon_Login Amazon_Payment

**Comment by srenon** [comment]
I will look into that.... but to my knowledge, this issue stems from a partial fix to fix multi-store sending the wrong email template. If I remember correctly this was introduced during a contribution day effect and the solution was just overly complex

**Comment by InternetMedicineMan** [comment]
I just know my problem went away when I disabled the Amazon modules. I read the issue reports and there were a few core mods that people were placing, and then a couple people recommended just disabling the Amazon modules and worked like a charm with no work arounds needed.
