### ISSUE TITLE
Not compatible with Magento 2.3.0

### ISSUE THREAD

**Issue by webspeaks** [magepal/magento2-gmail-smtp-app#125]
This plugin seems to be incompatible with Magento 2.3.0. When I try to send any email,
it gives the following error in logs:
```
PHP Fatal error:  Uncaught Error: Call to undefined method Magento\Framework\Mail\Message\Interceptor::getFrom() in /magento1/vendor/magepal/magento2-gmailsmtpapp/Plugin/Mail/TransportPlugin.php:75
Stack trace:
#0 /magento2/vendor/magepal/magento2-gmailsmtpapp/Plugin/Mail/TransportPlugin.php(49): MagePal\GmailSmtpApp\Plugin\Mail\TransportPlugin->sendSmtpMessage(Object(Magento\Framework\Mail\Message\Interceptor))
#1 /magento2/vendor/magento/framework/Interception/Interceptor.php(135): MagePal\GmailSmtpApp\Plugin\Mail\TransportPlugin->aroundSendMessage(Object(Magento\Email\Model\Transport\Interceptor), Object(Closure))
#2 /magento2/vendor/dotmailer/dotmailer-magento2-extension/Plugin/TransportPlugin.php(74): Magento\Email\Model\Transport\Interceptor->Magento\Framework\Interception\{closure}()
#3 /magento2/vendor/magento/framework/Interception/Interceptor.php(135): Dotdigitalgroup\Email\ in /magento2/vendor/magepal/magento2-gmailsmtpapp/Plugin/Mail/TransportPlugin.php on line 75

```
Also during code compile, It gives following error:
```
-bash-4.2$ php bin/magento setup:d:c
Compilation was started.
Area configuration aggregation... 5/7 [====================>-------]  71% 40 secs 364.0 MiB
In ClassReader.php line 35:
  Class Magento\Email\Model\Source\Variables does not exist
In ClassReader.php line 29:
  Class Magento\Email\Model\Source\Variables does not exist

```

**Comment by srenon** [comment]
@webspeaks ... what version of our extension are you using?

> root@magentoos23:magentoOS2.3/magento2ce# php bin/magento setup:di:compile
> Compilation was started.
> Interception cache generation... 7/7 [============================] 100% 1 min 317.0 MiB
> Generated code and dependency injection configuration successfully.

Plus I know of other clients running our extension on 2.3.0

**Comment by srenon** [comment]
I will have an update shortly to address ```Call to undefined method Magento\Framework\Mail\Message\Interceptor::getFrom() ```

**Comment by webspeaks** [comment]
@srenon I just installed the fresh extension yesterday. So it should be on the latest version.

**Comment by Artem-Schander** [comment]
FYI
In [TransportPlugin@sendSmtpMessage](https://github.com/magepal/magento2-gmail-smtp-app/blob/5f6fdb0ca22ae69f4f015ed87bc32ed9629d377e/Plugin/Mail/TransportPlugin.php#L119) `$message` is not instance of Zend_Mail.
Besides that, [`$message->setReturnPath($returnPathEmail);` ](https://github.com/magepal/magento2-gmail-smtp-app/blob/5f6fdb0ca22ae69f4f015ed87bc32ed9629d377e/Plugin/Mail/TransportPlugin.php#L86)
and [`$message->setReplyTo($returnPathEmail);`](https://github.com/magepal/magento2-gmail-smtp-app/blob/5f6fdb0ca22ae69f4f015ed87bc32ed9629d377e/Plugin/Mail/TransportPlugin.php#L90) are not available too.

**Comment by srenon** [comment]
@Artem-Schander .... I know... I'm working on a patch

**Comment by Artem-Schander** [comment]
@srenon 
Let me know if i can help somehow ;)

**Comment by srenon** [comment]
@webspeaks & @Artem-Schander ... can you test 2.6.0 and let me know if you have any issues?

**Comment by webspeaks** [comment]
@srenon I updated to latest version. But still facing the same issue.
![image](https://user-images.githubusercontent.com/1465109/49495960-a60f5c80-f88a-11e8-8ddf-a925414823b4.png)

**Comment by Artem-Schander** [comment]
For me it works fine. Many Thanks @srenon !

**Comment by srenon** [comment]
@webspeaks ... that class is not used in our module, so try to disable/remove our module and try di:compile to see if the issue still exists.

Also, do a search for "Magento\Email\Model\Source\Variables" they should be only one instance of it in dev/tests/static/testsuite/Magento/Test/Legacy/_files/obsolete_classes.php

**Comment by srenon** [comment]
@Artem-Schander ... Thanks, 

Also, did you run di:compile?

**Comment by Artem-Schander** [comment]
Yep. I've successfully run the cache / setup / compile commands.

**Comment by webspeaks** [comment]
@Artem-Schander It is fixed now. It was the issue with some other extension.
Sorry for the false alarm.
