### ISSUE TITLE
SUBJ_ILLEGAL_CHARS	Subject: has too many raw illegal characters

### ISSUE THREAD

**Issue by mvenghaus** [magepal/magento2-gmail-smtp-app#127]
Hello,

we're sending our emails in german. And it seems that the subject is not send as utf8!?

Would be nice if you can help :)

Regards
Marcus

**Comment by srenon** [comment]
could you provide more information... like what version of Magento and this module are you using

**Comment by mvenghaus** [comment]
Magento 2.3 and 1.2 from your module

**Comment by mvenghaus** [comment]
I've found a workaround/fix for me.

https://github.com/magepal/magento2-gmail-smtp-app/blob/master/Model/TwoDotThree/Smtp.php#L74

Here the message is created. The default is ASCII so the encoding of the header is also set to ASCII and it's not changed after that. When I add the following line everything works. Don't know if that's the right place for the fix!?

```
$message = Message::fromString($message->getRawMessage());
$message->getHeaders()->setEncoding('utf-8');
```

Regards
Marcus

**Comment by srenon** [comment]
@mvenghaus ... will be fixed in next update

**Comment by Artem-Schander** [comment]
Besides that Issue, there is a similar one:

![2019-04-09-093037_967x350_scrot](https://user-images.githubusercontent.com/1243826/55782970-af653b80-5aad-11e9-8858-c1bdf8b77103.png)

**Comment by mvenghaus** [comment]
That's not an extension issue .. it should be handled by magento .. but when you make all other things correct you don't have to care about this one,
