### ISSUE TITLE
ERROR 500 after subscribing or contact form 

### ISSUE THREAD

**Issue by Kgroop** [magepal/magento2-gmail-smtp-app#128]
Test email works but its receive a 500 request error 

#### Magento version #:
2.3
#### Edition (EE, CE, OS, etc):
OS
#### Expected behavior:
Send email and dont show error page
#### Actual behavior:
500 page
#### Steps to reproduce:
Subscibe or fill contact us page

**Comment by srenon** [comment]
@Kgroop .... Sorry we can not relicate this issue.

![image](https://user-images.githubusercontent.com/1415141/49701662-f2290c80-fbbc-11e8-9f7e-f5aee8b595ea.png)

**Comment by srenon** [comment]
@Kgroop ... what language are you using?
