### ISSUE TITLE
issue with sending reminder about password, activate link etc

### ISSUE THREAD

**Issue by devhero-tech** [magepal/magento2-gmail-smtp-app#131]
#### Magento version #:
2.3
#### Edition (EE, CE, OS, etc):
ce
#### Expected behavior:
send email
#### Actual behavior:
white page with exception in logs
#### Steps to reproduce:
go to password reminder, put proper email, click send -> white page
#### Preconditions

[Thu Jan 03 14:42:35.980019 2019] [php7:error] [pid 19385] [client 37.128.110.66:50041] PHP Fatal error:  Uncaught Error: Call to undefined method Zend\\Mail\\Message::clearFrom() in vendor/magepal/magento2-gmailsmtpapp/Model/TwoDotThree/Smtp.php:104\nStack trace:\n#0 vendor/magepal/magento2-gmailsmtpapp/Plugin/Mail/TransportPlugin.php(57): MagePal\\GmailSmtpApp\\Model\\TwoDotThree\\Smtp->sendSmtpMessage(Object(Zend\\Mail\\Message))\n#1 vendor/magento/framework/Interception/Interceptor.php(135): MagePal\\GmailSmtpApp\\Plugin\\Mail\\TransportPlugin->aroundSendMessage(Object(Magento\\Email\\Model\\Transport\\Interceptor), Object(Closure))\n#2 vendor/magento/module-email/Model/Mail/TransportInterfacePlugin.php(48): Magento\\Email\\Model\\Transport\\Interceptor->Magento\\Framework\\Interception\\{closure}()\n#3 vendor/magento/framework/Interception/Interceptor.php(135): Magento\\Email\\Model\\Mail\\TransportInter in vendor/magepal/magento2-gmailsmtpapp/Model/TwoDotThree/Smtp.php on line 104, referer: https://example.com/customer/account/forgotpassword/

**Comment by srenon** [comment]
@devhero-tech ... please upgrade to  v2.6.1
