### ISSUE TITLE
Magepal GmailSmtpApp empty configuration

### ISSUE THREAD

**Issue by Nicatgenglobal** [magepal/magento2-gmail-smtp-app#132]
#### Expected behavior: 
I installed manually Magepal GmailSmtpApp following instructions. all good via composer. 
Expected behavior: 

1. to see the configuration in Store --> Configuration --> Magepal --> Smtp Configuration
2. to see the configuration page in Store --> Configuration -->Advanced --> System

#### Actual behavior:
Both pages are completely empty

I found a couple of related issues open and closed but no solution.

Please, anyone came across the same issue?
![image](https://user-images.githubusercontent.com/46499673/50858412-42e08080-1388-11e9-85fb-2397a81b8471.png)

Thanks in advance.

Nick

**Comment by srenon** [comment]
@Nicatgenglobal... Could you check your PHP error log?

**Comment by Nicatgenglobal** [comment]
2 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): Invalid block type: MagePal\GmailSmtpApp\Block\Adminhtml\System\Config\Form\Module\Version
Exception #1 (ReflectionException): Class MagePal\GmailSmtpApp\Block\Adminhtml\System\Config\Form\Module\Version does not exist

Exception #0 (Magento\Framework\Exception\LocalizedException): Invalid block type: MagePal\GmailSmtpApp\Block\Adminhtml\System\Config\Form\Module\Version
#0 /home/gengloba/public_html/vendor/magento/framework/View/Layout/Generator/Block.php(249): Magento\Framework\View\Layout\Generator\Block->getBlockInstance('MagePal\\GmailSm...', Array)
#1 /home/gengloba/public_html/vendor/magento/framework/View/Layout.php(776): Magento\Framework\View\Layout\Generator\Block->createBlock('MagePal\\GmailSm...', 'adminhtml\\syste...', Array)
#2 /home/gengloba/public_html/vendor/magento/framework/View/Layout.php(759): Magento\Framework\View\Layout->_createBlock('MagePal\\GmailSm...', 'adminhtml\\syste...', Array)
#3 /home/gengloba/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(349): Magento\Framework\View\Layout->createBlock('MagePal\\GmailSm...', 'adminhtml\\syste...', Array)
#4 /home/gengloba/public_html/vendor/magento/framework/View/Layout.php(989): Magento\Framework\View\Layout\Interceptor->createBlock('MagePal\\GmailSm...')
#5 /home/gengloba/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(518): Magento\Framework\View\Layout->getBlockSingleton('MagePal\\GmailSm...')
#6 /home/gengloba/public_html/vendor/magento/module-config/Block/System/Config/Form.php(353): Magento\Framework\View\Layout\Interceptor->getBlockSingleton('MagePal\\GmailSm...')
#7 /home/gengloba/public_html/vendor/magento/module-config/Block/System/Config/Form.php(325): Magento\Config\Block\System\Config\Form->_initElement(Object(Magento\Config\Model\Config\Structure\Element\Field\Interceptor), Object(Magento\Framework\Data\Form\Element\Fieldset), 'magepal_gmailsm...', '', '')
#8 /home/gengloba/public_html/vendor/magento/module-config/Block/System/Config/Form.php(265): Magento\Config\Block\System\Config\Form->initFields(Object(Magento\Framework\Data\Form\Element\Fieldset), Object(Magento\Config\Model\Config\Structure\Element\Group\Interceptor), Object(Magento\Config\Model\Config\Structure\Element\Section))
#9 /home/gengloba/public_html/vendor/magento/module-config/Block/System/Config/Form.php(211): Magento\Config\Block\System\Config\Form->_initGroup(Object(Magento\Config\Model\Config\Structure\Element\Group\Interceptor), Object(Magento\Config\Model\Config\Structure\Element\Section), Object(Magento\Framework\Data\Form))
#10 /home/gengloba/public_html/vendor/magento/module-config/Block/System/Config/Form.php(548): Magento\Config\Block\System\Config\Form->initForm()
#11 /home/gengloba/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(667): Magento\Config\Block\System\Config\Form->_beforeToHtml()
#12 /home/gengloba/public_html/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Element\AbstractBlock->toHtml()
#13 /home/gengloba/public_html/vendor/magento/framework/View/Layout.php(533): Magento\Framework\View\Layout->_renderBlock('system\\config\\f...')
#14 /home/gengloba/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('system\\config\\f...')
#15 /home/gengloba/public_html/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('system\\config\\f...')
#16 /home/gengloba/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('system\\config\\f...', true)
#17 /home/gengloba/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(508): Magento\Framework\View\Layout\Interceptor->renderElement('system\\config\\f...', true)
#18 /home/gengloba/public_html/vendor/magento/module-config/view/adminhtml/templates/system/config/edit.phtml(28): Magento\Framework\View\Element\AbstractBlock->getChildHtml('form')
#19 /home/gengloba/public_html/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/home/gengloba/...')
#20 /home/gengloba/public_html/vendor/magento/framework/View/Element/Template.php(271): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Config\Block\System\Config\Edit), '/home/gengloba/...', Array)
#21 /home/gengloba/public_html/vendor/magento/framework/View/Element/Template.php(301): Magento\Framework\View\Element\Template->fetchView('/home/gengloba/...')
#22 /home/gengloba/public_html/vendor/magento/module-backend/Block/Template.php(129): Magento\Framework\View\Element\Template->_toHtml()
#23 /home/gengloba/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(668): Magento\Backend\Block\Template->_toHtml()
#24 /home/gengloba/public_html/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Element\AbstractBlock->toHtml()
#25 /home/gengloba/public_html/vendor/magento/framework/View/Layout.php(533): Magento\Framework\View\Layout->_renderBlock('system.config.e...')
#26 /home/gengloba/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('system.config.e...')
#27 /home/gengloba/public_html/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('system.config.e...')
#28 /home/gengloba/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('system.config.e...', false)
#29 /home/gengloba/public_html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('system.config.e...', false)
#30 /home/gengloba/public_html/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('content', false)
#31 /home/gengloba/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('content')
#32 /home/gengloba/public_html/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('content')
#33 /home/gengloba/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('content', false)
#34 /home/gengloba/public_html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('content', false)
#35 /home/gengloba/public_html/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('admin.scope.col...', false)
#36 /home/gengloba/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('admin.scope.col...')
#37 /home/gengloba/public_html/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('admin.scope.col...')
#38 /home/gengloba/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('admin.scope.col...', false)
#39 /home/gengloba/public_html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('admin.scope.col...', false)
#40 /home/gengloba/public_html/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('main.col', false)
#41 /home/gengloba/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('main.col')
#42 /home/gengloba/public_html/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main.col')
#43 /home/gengloba/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('main.col', false)
#44 /home/gengloba/public_html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('main.col', false)
#45 /home/gengloba/public_html/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('page.main.conta...', false)
#46 /home/gengloba/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.main.conta...')
#47 /home/gengloba/public_html/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.main.conta...')
#48 /home/gengloba/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.main.conta...', false)
#49 /home/gengloba/public_html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('page.main.conta...', false)
#50 /home/gengloba/public_html/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('page.content', false)
#51 /home/gengloba/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.content')
#52 /home/gengloba/public_html/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.content')
#53 /home/gengloba/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.content', false)
#54 /home/gengloba/public_html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('page.content', false)
#55 /home/gengloba/public_html/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('page.wrapper', false)
#56 /home/gengloba/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#57 /home/gengloba/public_html/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.wrapper')
#58 /home/gengloba/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.wrapper', false)
#59 /home/gengloba/public_html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('page.wrapper', false)
#60 /home/gengloba/public_html/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('backend.page', false)
#61 /home/gengloba/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('backend.page')
#62 /home/gengloba/public_html/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('backend.page')
#63 /home/gengloba/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('backend.page', false)
#64 /home/gengloba/public_html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('backend.page', false)
#65 /home/gengloba/public_html/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('root', false)
#66 /home/gengloba/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('root')
#67 /home/gengloba/public_html/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root')
#68 /home/gengloba/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('root', true)
#69 /home/gengloba/public_html/vendor/magento/framework/View/Layout.php(954): Magento\Framework\View\Layout\Interceptor->renderElement('root')
#70 /home/gengloba/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(492): Magento\Framework\View\Layout->getOutput()
#71 /home/gengloba/public_html/vendor/magento/framework/View/Result/Page.php(258): Magento\Framework\View\Layout\Interceptor->getOutput()
#72 /home/gengloba/public_html/vendor/magento/framework/View/Result/Layout.php(171): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#73 /home/gengloba/public_html/generated/code/Magento/Backend/Model/View/Result/Page/Interceptor.php(193): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#74 /home/gengloba/public_html/vendor/magento/framework/App/Http.php(139): Magento\Backend\Model\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#75 /home/gengloba/public_html/generated/code/Magento/Framework/App/Http/Interceptor.php(24): Magento\Framework\App\Http->launch()
#76 /home/gengloba/public_html/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http\Interceptor->launch()
#77 /home/gengloba/public_html/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#78 {main}

Exception #1 (ReflectionException): Class MagePal\GmailSmtpApp\Block\Adminhtml\System\Config\Form\Module\Version does not exist
#0 /home/gengloba/public_html/vendor/magento/framework/Code/Reader/ClassReader.php(19): ReflectionClass->__construct('MagePal\\GmailSm...')
#1 /home/gengloba/public_html/vendor/magento/framework/ObjectManager/Definition/Runtime.php(49): Magento\Framework\Code\Reader\ClassReader->getConstructor('MagePal\\GmailSm...')
#2 /home/gengloba/public_html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(48): Magento\Framework\ObjectManager\Definition\Runtime->getParameters('MagePal\\GmailSm...')
#3 /home/gengloba/public_html/vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('MagePal\\GmailSm...', Array)
#4 /home/gengloba/public_html/vendor/magento/framework/View/Element/BlockFactory.php(46): Magento\Framework\ObjectManager\ObjectManager->create('MagePal\\GmailSm...', Array)
#5 /home/gengloba/public_html/vendor/magento/framework/View/Layout/Generator/Block.php(269): Magento\Framework\View\Element\BlockFactory->createBlock('MagePal\\GmailSm...', Array)
#6 /home/gengloba/public_html/vendor/magento/framework/View/Layout/Generator/Block.php(249): Magento\Framework\View\Layout\Generator\Block->getBlockInstance('MagePal\\GmailSm...', Array)
#7 /home/gengloba/public_html/vendor/magento/framework/View/Layout.php(776): Magento\Framework\View\Layout\Generator\Block->createBlock('MagePal\\GmailSm...', 'adminhtml\\syste...', Array)
#8 /home/gengloba/public_html/vendor/magento/framework/View/Layout.php(759): Magento\Framework\View\Layout->_createBlock('MagePal\\GmailSm...', 'adminhtml\\syste...', Array)
#9 /home/gengloba/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(349): Magento\Framework\View\Layout->createBlock('MagePal\\GmailSm...', 'adminhtml\\syste...', Array)
#10 /home/gengloba/public_html/vendor/magento/framework/View/Layout.php(989): Magento\Framework\View\Layout\Interceptor->createBlock('MagePal\\GmailSm...')
#11 /home/gengloba/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(518): Magento\Framework\View\Layout->getBlockSingleton('MagePal\\GmailSm...')
#12 /home/gengloba/public_html/vendor/magento/module-config/Block/System/Config/Form.php(353): Magento\Framework\View\Layout\Interceptor->getBlockSingleton('MagePal\\GmailSm...')
#13 /home/gengloba/public_html/vendor/magento/module-config/Block/System/Config/Form.php(325): Magento\Config\Block\System\Config\Form->_initElement(Object(Magento\Config\Model\Config\Structure\Element\Field\Interceptor), Object(Magento\Framework\Data\Form\Element\Fieldset), 'magepal_gmailsm...', '', '')
#14 /home/gengloba/public_html/vendor/magento/module-config/Block/System/Config/Form.php(265): Magento\Config\Block\System\Config\Form->initFields(Object(Magento\Framework\Data\Form\Element\Fieldset), Object(Magento\Config\Model\Config\Structure\Element\Group\Interceptor), Object(Magento\Config\Model\Config\Structure\Element\Section))
#15 /home/gengloba/public_html/vendor/magento/module-config/Block/System/Config/Form.php(211): Magento\Config\Block\System\Config\Form->_initGroup(Object(Magento\Config\Model\Config\Structure\Element\Group\Interceptor), Object(Magento\Config\Model\Config\Structure\Element\Section), Object(Magento\Framework\Data\Form))
#16 /home/gengloba/public_html/vendor/magento/module-config/Block/System/Config/Form.php(548): Magento\Config\Block\System\Config\Form->initForm()
#17 /home/gengloba/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(667): Magento\Config\Block\System\Config\Form->_beforeToHtml()
#18 /home/gengloba/public_html/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Element\AbstractBlock->toHtml()
#19 /home/gengloba/public_html/vendor/magento/framework/View/Layout.php(533): Magento\Framework\View\Layout->_renderBlock('system\\config\\f...')
#20 /home/gengloba/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('system\\config\\f...')
#21 /home/gengloba/public_html/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('system\\config\\f...')
#22 /home/gengloba/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('system\\config\\f...', true)
#23 /home/gengloba/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(508): Magento\Framework\View\Layout\Interceptor->renderElement('system\\config\\f...', true)
#24 /home/gengloba/public_html/vendor/magento/module-config/view/adminhtml/templates/system/config/edit.phtml(28): Magento\Framework\View\Element\AbstractBlock->getChildHtml('form')
#25 /home/gengloba/public_html/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/home/gengloba/...')
#26 /home/gengloba/public_html/vendor/magento/framework/View/Element/Template.php(271): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Config\Block\System\Config\Edit), '/home/gengloba/...', Array)
#27 /home/gengloba/public_html/vendor/magento/framework/View/Element/Template.php(301): Magento\Framework\View\Element\Template->fetchView('/home/gengloba/...')
#28 /home/gengloba/public_html/vendor/magento/module-backend/Block/Template.php(129): Magento\Framework\View\Element\Template->_toHtml()
#29 /home/gengloba/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(668): Magento\Backend\Block\Template->_toHtml()
#30 /home/gengloba/public_html/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Element\AbstractBlock->toHtml()
#31 /home/gengloba/public_html/vendor/magento/framework/View/Layout.php(533): Magento\Framework\View\Layout->_renderBlock('system.config.e...')
#32 /home/gengloba/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('system.config.e...')
#33 /home/gengloba/public_html/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('system.config.e...')
#34 /home/gengloba/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('system.config.e...', false)
#35 /home/gengloba/public_html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('system.config.e...', false)
#36 /home/gengloba/public_html/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('content', false)
#37 /home/gengloba/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('content')
#38 /home/gengloba/public_html/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('content')
#39 /home/gengloba/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('content', false)
#40 /home/gengloba/public_html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('content', false)
#41 /home/gengloba/public_html/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('admin.scope.col...', false)
#42 /home/gengloba/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('admin.scope.col...')
#43 /home/gengloba/public_html/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('admin.scope.col...')
#44 /home/gengloba/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('admin.scope.col...', false)
#45 /home/gengloba/public_html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('admin.scope.col...', false)
#46 /home/gengloba/public_html/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('main.col', false)
#47 /home/gengloba/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('main.col')
#48 /home/gengloba/public_html/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main.col')
#49 /home/gengloba/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('main.col', false)
#50 /home/gengloba/public_html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('main.col', false)
#51 /home/gengloba/public_html/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('page.main.conta...', false)
#52 /home/gengloba/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.main.conta...')
#53 /home/gengloba/public_html/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.main.conta...')
#54 /home/gengloba/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.main.conta...', false)
#55 /home/gengloba/public_html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('page.main.conta...', false)
#56 /home/gengloba/public_html/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('page.content', false)
#57 /home/gengloba/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.content')
#58 /home/gengloba/public_html/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.content')
#59 /home/gengloba/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.content', false)
#60 /home/gengloba/public_html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('page.content', false)
#61 /home/gengloba/public_html/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('page.wrapper', false)
#62 /home/gengloba/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#63 /home/gengloba/public_html/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.wrapper')
#64 /home/gengloba/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.wrapper', false)
#65 /home/gengloba/public_html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('page.wrapper', false)
#66 /home/gengloba/public_html/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('backend.page', false)
#67 /home/gengloba/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('backend.page')
#68 /home/gengloba/public_html/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('backend.page')
#69 /home/gengloba/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('backend.page', false)
#70 /home/gengloba/public_html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('backend.page', false)
#71 /home/gengloba/public_html/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('root', false)
#72 /home/gengloba/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('root')
#73 /home/gengloba/public_html/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root')
#74 /home/gengloba/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('root', true)
#75 /home/gengloba/public_html/vendor/magento/framework/View/Layout.php(954): Magento\Framework\View\Layout\Interceptor->renderElement('root')
#76 /home/gengloba/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(492): Magento\Framework\View\Layout->getOutput()
#77 /home/gengloba/public_html/vendor/magento/framework/View/Result/Page.php(258): Magento\Framework\View\Layout\Interceptor->getOutput()
#78 /home/gengloba/public_html/vendor/magento/framework/View/Result/Layout.php(171): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#79 /home/gengloba/public_html/generated/code/Magento/Backend/Model/View/Result/Page/Interceptor.php(193): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#80 /home/gengloba/public_html/vendor/magento/framework/App/Http.php(139): Magento\Backend\Model\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#81 /home/gengloba/public_html/generated/code/Magento/Framework/App/Http/Interceptor.php(24): Magento\Framework\App\Http->launch()
#82 /home/gengloba/public_html/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http\Interceptor->launch()
#83 /home/gengloba/public_html/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#84 {main}

**Comment by srenon** [comment]
I have not seen, could not replicate or have not idea why this issue occurs. No one has reported this issue in over a year. Can you try clearing cache and rerun setup:upgrade and di:compile

**Comment by Nicatgenglobal** [comment]
Thanks for your help.
However no solution yet.
Magento 2.3 has been released end of November. the bug history is limited of course. 

after di:compile the error differs

Fatal error: Uncaught Error: Class 'MagePal\GmailSmtpApp\Block\Adminhtml\System\Config\Form\Module\Version' not found in /home/gengloba/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:116 Stack trace: #0 /home/gengloba/public_html/vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('MagePal\\GmailSm...', Array) #1 /home/gengloba/public_html/vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Compiled->create('MagePal\\GmailSm...', Array) #2 /home/gengloba/public_html/vendor/magento/framework/View/Element/BlockFactory.php(46): Magento\Framework\ObjectManager\ObjectManager->create('MagePal\\GmailSm...', Array) #3 /home/gengloba/public_html/vendor/magento/framework/View/Layout/Generator/Block.php(269): Magento\Framework\View\Element\BlockFactory->createBlock('MagePal\\GmailSm...', Array) #4 /home/gengloba/public_html/vendor/magento/framework/View/Layout/Generator in /home/gengloba/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 116

**Comment by srenon** [comment]
I will not be able to fix it without the ability to replicate it. The only recommendation I can provide is to open a paid support so that I can better review the issue
