### ISSUE TITLE
don't receive any test mails

### ISSUE THREAD

**Issue by Paulinanana** [magepal/magento2-gmail-smtp-app#135]
I installed the extension on Magento 2.3. When i try to send a testmail i get the message "Oh Yeah!
Please check your email.." But i dont receive any mails. 

What could went wrong? 

Thank you!
Paulina

**Comment by Paulinanana** [comment]
I solved the issue. It was a problem with my email provider. Now everything is working fine! Thank you!

**Comment by Januszpl** [comment]
@Paulinanana what was exactly the issue with your email provider? I have test email but none of the magento emails.
