### ISSUE TITLE
"Sent Test Email" 404s

### ISSUE THREAD

**Issue by erfanimani** [magepal/magento2-gmail-smtp-app#136]
#### Magento version #:

Magento 2.3, PHP 7.2

#### Edition (EE, CE, OS, etc):

CE

#### Steps to reproduce:

* Log into admin
* Navigate to Store Configuration -> System
* Fill out "Test Email Server Configuration Settings" and hit "Send Test Email"

#### Expected behavior:

* Test email sent

#### Actual behavior:

* Message appears: "A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later."
* When inspecting the network tab in Chrome I can see that the URL 404s: https://example.com/admin_mysecreturl/magepalsmtp/test/index/key/f1fb612b17f728f5334332fba0883ae62bfb6c7fa04aebc936a14a2a6412f515/?isAjax=true

#### Preconditions

Magento 2.3.0, PHP 7.2.15

Normal emails work fine, however.

I don't see any adminhtml controllers in the module so maybe this is a known bug?

**Comment by srenon** [comment]
I'm not aware of any issue with PHP 7.2 and Magento 2.3. 

Admin controller - https://github.com/magepal/magento2-gmail-smtp-app/blob/master/Controller/Adminhtml/Test/Index.php

Admin layout xml - https://github.com/magepal/magento2-gmail-smtp-app/blob/master/view/adminhtml/layout/magepalsmtp_test_index.xml

**Comment by erfanimani** [comment]
Thanks for the fast response, sorry — it must be my bad then. I will investigate (in my haste I thought it was a unit test :')) and get back to you..

**Comment by erfanimani** [comment]
Ah, so I think I figured out the issue — it was working fine on my local, but not when I deployed to an environment. I realised the Test directory in `vendor/magepal/magento2-gmailsmtpapp/Controller/Adminhtml/` wasn't copied over upon deployment.

I'm using @jalogut's Magento 2 Deployer Plus for deployments and it looks like directories called "Test" are excluded: https://github.com/jalogut/magento2-deployer-plus/blob/master/config/artifact.excludes

I think that behaviour is correct — in Magento 2 you can have Test directory that houses your PHP unit tests which should not be deployed.

I think my opinion is to use a different directory name, but up to your discretion :)

**Comment by srenon** [comment]
I will rename that file in a future release

**Comment by erfanimani** [comment]
Thanks @srenon, much appreciated.

**Comment by srenon** [comment]
@erfanimani ... fixed in 2.6.2
