### ISSUE TITLE
Outgoing mail from "" has been suspended.

### ISSUE THREAD

**Issue by Sherkhan1991** [magepal/magento2-gmail-smtp-app#138]
I have installed the extension v1.2.9 and on the other side we have office365 mail

#### Magento version #:
2.2.5
#### Edition (EE, CE, OS, etc):
CE
#### Expected behavior:
The testing email should work
#### Actual behavior:
Could not open socket (i fix this using https://magento.stackexchange.com/questions/209227/magento-2-smtp-could-not-open-socket)
After that
When hit test email it shows "Outgoing mail from "" has been suspended."
Or the below exception
Warning: stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol in /home/boxesbox/staging.boxes2boxes.ca/vendor/magento/zendframework1/library/Zend/Mail/Protocol/Abstract.php on line 282

#### Steps to reproduce:
host: smtp.office365.com
port: 587
protocol: (TSL/SSL) both showing same error
Authentication: (login)
Developer mode:no

**Comment by srenon** [comment]
This is a server config issue and not a bug. 

More than likely you have an invalid SSL cert
