### ISSUE TITLE
Invalid argument supplied foreach

### ISSUE THREAD

**Issue by datwiki** [magepal/magento2-gmail-smtp-app#141]
#### Steps to reproduce:
1. Install latest version MagePal SMTP to Magento CE 2.2.8
2. Setup account Gmail as normal
3. Choose Specified Value for Set Return Path option
4. Provide any email as value
5. Hit Send Test Mail
<img width="514" alt="56718929-f28c0380-6769-11e9-8e88-b9c9c405bfd6" src="https://user-images.githubusercontent.com/11314414/56734022-f466be80-678b-11e9-94cf-3dbdd6ac279b.png">

**Comment by srenon** [comment]
@datwiki ... I will release a new version to fix this shortly.

Do you have any Mirasvit extension installed?

**Comment by datwiki** [comment]
hi @srenon , sorry for my late response.
Yes, in all our projects we use quite many Mirasvit extensions, is it a problem?

Thank you for your support

**Comment by srenon** [comment]
Yea, their extension rewrite some core Magento email logic for no reason to best of my knowledge.

I will add a fix in our next release which will be in few days to weeks time

**Comment by datwiki** [comment]
hi @srenon , oh, good to know that! Thanks for sharing.

And thanks again for your support!
Dat

**Comment by basvanpoppel** [comment]
Hi @srenon 

We ran into this issue as well. I just saw your PR from five days ago with the fix.

Do you have an estimation on when a new release is available containing the fix?

Thank you!

**Comment by saulable** [comment]
Yep, having same problem! :)

**Comment by srenon** [comment]
@saulable ... Do you have any Mirasvit extension installed?

**Comment by saulable** [comment]
> @saulable ... Do you have any Mirasvit extension installed?

Nope. Decided to go down the ssmtp config route.
