### ISSUE TITLE
Username and password not accepted

### ISSUE THREAD

**Issue by mrtuvn** [magepal/magento2-gmail-smtp-app#144]
Today i got this issue. Before that it's not happen. Not sure google update or restricts any security.
Credentials gmail saved and correctly
#### Actual behavior: Error bummer
![magepal](https://user-images.githubusercontent.com/1908873/59526306-d2272c80-8f02-11e9-930d-67289ab5837d.PNG)

#### Steps to reproduce: Go to configuration MagePal. Add mail credentials
add test email send for test purpose

#### Preconditions
Log magento var/log/exception.log

[2019-06-14 17:37:29] main.CRITICAL: 5.7.8 Username and Password not accepted. Learn more at
 5.7.8  https://support.google.com/mail/?p=BadCredentials - gsmtp
 {"exception":"[object] (Magento\\Framework\\Exception\\MailException(code: 0): 5.7.8 Username and Password not accepted. Learn more at
 5.7.8  https://support.google.com/mail/?p=BadCredentials - gsmtp
 at /var/www/html/app/code/MagePal/GmailSmtpApp/Model/ZendMailTwo/Smtp.php:158, Zend\\Mail\\Protocol\\Exception\\RuntimeException(code: 0): 5.7.8 Username and Password not accepted. Learn more at
 5.7.8  https://support.google.com/mail/?p=BadCredentials  - gsmtp
 at /var/www/html/vendor/zendframework/zend-mail/src/Protocol/AbstractProtocol.php:348)"} [

**Comment by mohxani** [comment]
- login to gmail account.
- go to account
- turn ON Less secure app access
now try sending it
Thanks
