### ISSUE TITLE
Office 365 Issue?

### ISSUE THREAD

**Issue by Ackater** [magepal/magento2-gmail-smtp-app#145]
Trying to get this working with Office 365, and it seems to fail the test email with 

>5.2.0 STOREDRV.Submission.Exception:SendAsDeniedException.MapiExceptionSendAsDenied; Failed to process message due to a permanent exception with message Cannot submit message. 

I think it's something to do with the From Info name? I think it works fine if it isn't an email. At the very least that gets it to pass the test, and my 'contact me' form works.

**Comment by srenon** [comment]
@Ackater ... take a look 2.6.4
