### ISSUE TITLE
Magento 2.2.9 "We can't save the customer" caused by this module

### ISSUE THREAD

**Issue by Neusta-Hartwig** [magepal/magento2-gmail-smtp-app#146]
#### Magento version #:
2.2.9

#### Edition (EE, CE, OS, etc):
CE

#### Expected behavior:
When new customer registers, the user is redirected to the user account. 

#### Actual behavior:
User is redirected to registration page with error message "We can't save the customer"

#### Steps to reproduce:

- Use a single email in the backends return path settings.
- Register via magentos registration page
-OR-
- just send a tesmail via backend

#### Preconditions
- Zendmail 2

#### Solution
Change file Model/ZendMailTwo/Smtp.php
`
if ($message->getReplyTo() === null && $dataHelper->getConfigSetReplyTo()) {
            foreach ($returnPathEmail as $address) {
                $message->setReplyTo($address);
            }
        }

        if ($returnPathEmail !== null && $dataHelper->getConfigSetFrom()) {
            foreach ($returnPathEmail as $address) {
                $message->setFrom($address);
            }
        }
`

to

`
if ($message->getReplyTo() === null && $dataHelper->getConfigSetReplyTo()) {
            if (is_string($returnPathEmail)) {
                $message->setReplyTo(trim($returnPathEmail));
            } elseif ($returnPathEmail instanceof AddressList) {
                foreach ($returnPathEmail as $address) {
                    $message->setReplyTo($address);
                }
            }
        }

        if ($returnPathEmail !== null && $dataHelper->getConfigSetFrom()) {
            if (is_string($returnPathEmail)) {
                $message->setFrom(trim($returnPathEmail));
            } elseif ($returnPathEmail instanceof AddressList) {
                foreach ($returnPathEmail as $address) {
                    $message->setFrom($address);
                }
            }
        }`

**Comment by srenon** [comment]
I will release a new version shortly... Do you have any Mirasvit extensions installed?

**Comment by Neusta-Hartwig** [comment]
> I will release a new version shortly
thx :)

> Do you have any Mirasvit extensions installed?
No, i don't have any Miravisit extension installed.

**Comment by srenon** [comment]
@Neusta-Hartwig ... Fixed in 2.6.4
