### ISSUE TITLE
Magento 2.3.3 support

### ISSUE THREAD

**Issue by franckgarnier21** [magepal/magento2-gmail-smtp-app#149]
Hello,

For Magento 2.3.3 support:

I think there is an issue with MessageInterface which has been changed with : EmailMessageInterface.

Thanks,

**Comment by srenon** [comment]
@franckgarnier21 ... could you provide more information on the issue you are having?

What version of our extension are you running?

https://github.com/magento/magento2/tree/2.3-develop/lib/internal/Magento/Framework/Mail

![image](https://user-images.githubusercontent.com/1415141/65890751-66fa4c80-e371-11e9-9a4b-5c4be018d02c.png)

**Comment by franckgarnier21** [comment]
Hello,

I am using 2.6.4 through composer.

The Magento TransportBuilder has changed the factory interface of EmailMessage here : https://github.com/magento/magento2/blob/2.3-develop/lib/internal/Magento/Framework/Mail/Template/TransportBuilder.php:167

Commit reference: https://github.com/magento/magento2/commit/3a90a0f61e953c8b943b8242525e77477cee8455#diff-dfb3ee5a7f863458afea75f5524cd2e5

So your plugin condition here vendor/magepal/magento2-gmailsmtpapp/Plugin/Mail/TransportPlugin.php:72 is not correct now.

And also in your Smtp implementation : vendor/magepal/magento2-gmailsmtpapp/Model/ZendMailTwo/Smtp.php:81

Hope it will help you.

I already made the change in my project for Magento 2.3.3 pre-release.

**Comment by Yonn-Trimoreau** [comment]
@franckgarnier21 Can you make a pull request or share your fixes?

**Comment by srenon** [comment]
@Yonn-Trimoreau ... I will release a new version once 2.3.3 is release

**Comment by Yonn-Trimoreau** [comment]
Magento 2.3.3 was released today!
https://devdocs.magento.com/guides/v2.3/release-notes/release-notes-2-3-3-open-source.html

**Comment by srenon** [comment]
@Yonn-Trimoreau ... please try v2.6.5 and let me know if you have any issue
