### ISSUE TITLE
Transaction failed: Expected disposition, got =

### ISSUE THREAD

**Issue by elfeffe** [magepal/magento2-gmail-smtp-app#153]
I'm using Magento 2.3.3, PHP 7.3, Ubuntu 18.04
And Amazon SES
If I use port 465 with SSL, I get `Transaction failed: Expected disposition, got =`
587 with SSL I get `Could not open socket`
Port 25 with SSL I get `Could not open socket`

Emails seem to be sending, I receive Hello from MagePal SMTP (1 of 2) emails, never 2 of 2, is there any 2 of 2?

The biggest problem is that the customers see that error on frontpage

**Comment by elfeffe** [comment]
Culd not open socket seems to be related to Vultr.com settings.
But I get `Transaction failed: Expected disposition, got =` with every setup, I can't get it work without the error message.

**Comment by cylix99** [comment]
Seems to be a Magento problem. The same problem occurs using Magplaza and SES. As yet i cannot find a fix

**Comment by srenon** [comment]
@cylix99 

"Could not open socket", normally mean something is blocked or server configuration issue.

1. Try some of the debugging steps at https://www.magepal.com/help/docs/smtp-magento/ to try to isolate your issue. 

2. Try testing with a different SMTP server (ie Gmail, office365 etc), to rule out server issue

3. Try using fake info to see if the error message change

**Comment by wilhelmpa** [comment]
Same error here: Transaction failed: Expected disposition, got =

any ideas?

**Comment by srenon** [comment]
@elfeffe @wilhelmpa ... please download 2.6.7 and let me know if you still having issues
