### ISSUE TITLE
Support PHP 7.3.10

### ISSUE THREAD

**Issue by otamate** [magepal/magento2-gmail-smtp-app#154]
#### Magento version #:
2.3.3
#### Edition (EE, CE, OS, etc):
CE
#### Expected behavior:
Compatibile with PHP 7.3.10
#### Actual behavior:
Incompatibile with PHP 7.3.10
#### Steps to reproduce:
Attempt to update when running PHP 7.3.10

**Comment by srenon** [comment]
@otamate ... could you please add the error message

**Comment by octoxan** [comment]
`PHP Fatal error:  Uncaught TypeError: Argument 1 passed to MagePal\GmailSmtpApp\Plugin\Mail\TransportPlugin::sendSmtpMessage() must implement interface Magento\Framework\Mail\MessageInterface, instance of Magento\Framework\Mail\EmailMessage given` is the error I get, whenever I go to place orders, only on 7.3

**Comment by srenon** [comment]
What version of our extension are you using?
