### ISSUE TITLE
Uncaught Error: Call to a member function setEncoding() on bool

### ISSUE THREAD

**Issue by jamie-selesti** [magepal/magento2-gmail-smtp-app#166]
#### Magento version #:
Magento 2.3.3

#### Edition (EE, CE, OS, etc):
CE

#### Expected behavior:
To receive 2 emails

1. Hello from MagePal SMTP (1 of 2)

1. Hello from MagePal SMTP (2 of 2)

#### Actual behavior:

- Only receive "Hello from MagePal SMTP (1 of 2)" email

- An error is displayed in the admin "A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later."

- Looking at the error log I can see

`PHP Fatal error:  Uncaught Error: Call to a member function setEncoding() on bool in /var/www/vhosts/domain.com/vendor/magepal/magento2-gmailsmtpapp/Model/TwoDotThree/Smtp.php:83
Stack trace:
#0 /var/www/vhosts/domain.com/vendor/magepal/magento2-gmailsmtpapp/Plugin/Mail/TransportPlugin.php(79): MagePal\GmailSmtpApp\Model\TwoDotThree\Smtp->sendSmtpMessage(Object(Zend\Mail\Message))
#1 /var/www/vhosts/domain.com/vendor/magento/framework/Interception/Interceptor.php(135): MagePal\GmailSmtpApp\Plugin\Mail\TransportPlugin->aroundSendMessage(Object(Magento\Email\Model\Transport\Interceptor), Object(Closure))
#2 /var/www/vhosts/domain.com/vendor/magento/module-email/Model/Mail/TransportInterfacePlugin.php(48): Magento\Email\Model\Transport\Interceptor->Magento\Framework\Interception\{closure}()
#3 /var/www/vhosts/domain.com/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Email\Model\Mail\TransportInterfacePlugin->aroundSendMessage(Object(Magento\Email\Model\Transport\Interceptor), Object(C in /var/www/vhosts/domain.com/vendor/magepal/magento2-gmailsmtpapp/Model/TwoDotThree/Smtp.php on line 83
`

#### Steps to reproduce:

Send test email using the built-in "Test Email Server Configuration Settings" functionality

#### Preconditions
Extension settings can be seen in the screenshot below
![image](https://user-images.githubusercontent.com/1398649/77621780-04a39280-6f35-11ea-85b1-c13a083a51b2.png)

**Comment by woakley** [comment]
A quick and lazy fix is to comment out line 83.

**Comment by srenon** [comment]
This issue should be fixed in 2.8.0 which will be released shortly

**Comment by srenon** [comment]
@jamie-selesti @woakley ... please download 2.8.0 and let me know if you are still having issues
