### ISSUE TITLE
Backend javascript 404 error, not sending emails after update to 2.8.5

### ISSUE THREAD

**Issue by msbt** [magepal/magento2-gmail-smtp-app#173]
#### Magento version #:

2.2.11 CE running in on Ubuntu 18.04 in a Docker environment

#### Expected behavior:

Send (Test-)Emails

#### Actual behavior:

Says it sends emails (frontend) but it doesn't or won't allow the test-button to be clicked in backend.

#### Steps to reproduce:

Updated from 2.7.0 after realizing that there was this error in the logs:

```
2020-09-24 09:31:10] main.CRITICAL: Invalid header value detected {"exception":"[object] (Magento\\Framework\\Exception\\MailException(code: 0): Invalid header value detected at /app/data/public/vendor/magepal/magento2-gmailsmtpapp/Model/ZendMailTwo/Smtp.php:179, Zend\\Mail\\Header\\Exception\\RuntimeException(code: 0): Invalid header value detected at /app/data/public/vendor/zendframework/zend-mail/src/Header/HeaderValue.php:112)"} []
```

When trying to send with the Send Test Mail button in the backend, this 404 error shows up:

GET `https://website.host/pub/static/version1600943863/adminhtml/Magento/backend/de_DE/magePalGmailSmtpAppValidateConfig.min.js`

Which results in `Error: Script error for: magePalGmailSmtpAppValidateConfig`

#### Preconditions

Still on PHP 7.0 due to some other plugin and an unmaintained theme, might that be it?

Best regards,
M

**Comment by msbt** [comment]
ok correction: the password recovery email just arrived, got delayed due to greylisting, but the send test still doesn't work, which leaves a bad feeling ;)

**Comment by srenon** [comment]
@msbt ... let me know if you still having issues?

**Comment by msbt** [comment]
well the test-email in the adminpanel still doesn't work due to the `magePalGmailSmtpAppValidateConfig` script error
