### ISSUE TITLE
Version is fixed in composer.json

### ISSUE THREAD

**Issue by aboritskiy** [magepal/magento2-gmail-smtp-app#178]
#### Magento version #:

not magento specific, problem has to do with composer.

#### Expected behavior:

can install any tagged version from github.

#### Actual behavior:

can not install 2.8.6

#### Steps to reproduce:

try to do` composer require "magepal/magento2-gmailsmtpapp" "^2.8.6"`
it won't work, cause composer.json has version `2.8.5` in it.

suggestion: please remove the module version from composer.json, see
https://github.com/magepal/magento2-gmail-smtp-app/blob/master/composer.json#L25

see also https://getcomposer.org/doc/articles/versions.md

**Comment by srenon** [comment]
@aboritskiy ... Fixed

**Comment by aboritskiy** [comment]
@srenon thx for quick fix.

I still recommend to consider removing version from composer.json, cause it is per official composer recommendation.
I couldn't find the place where composer recommends it when I was opening the issue, but now I found it:

> Optional if the package repository can infer the version from somewhere, such as the VCS tag name in the VCS repository. In that case it is also recommended to omit it.

see https://getcomposer.org/doc/04-schema.md#version
