### ISSUE TITLE
lack of information about license of this package

### ISSUE THREAD

**Issue by tompianta** [magepal/magento2-gmail-smtp-app#182]
this package lack of a text file explaining under which kind of license it is released... if any.

**Comment by srenon** [comment]
@tompianta ... all our extensions are released under a 'proprietary' license (https://github.com/magepal/magento2-gmail-smtp-app/blob/master/composer.json#L26) which "helps" prevent other extensions company from just copying our code and do a find and replace for "MagePal" and call it there extension
