### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Laminas\Mail\Transport\SmtpOptions' not found in

### ISSUE THREAD

**Issue by nomadicshiv** [magepal/magento2-gmail-smtp-app#184]
Fatal error: Uncaught Error: Class 'Laminas\Mail\Transport\SmtpOptions' not found in /home/m3.lasthash.com/public_html/app/code/MagePal/GmailSmtpApp/Block/Adminhtml/ValidateConfig.php:288 Stack trace: #0 /home/m3.lasthash.com/public_html/app/code/MagePal/GmailSmtpApp/Block/Adminhtml/ValidateConfig.php(214): MagePal\GmailSmtpApp\Block\Adminhtml\ValidateConfig->validateServerEmailSetting() #1 /home/m3.lasthash.com/public_html/app/code/MagePal/GmailSmtpApp/view/adminhtml/templates/validateConfig/result.phtml(164): MagePal\GmailSmtpApp\Block\Adminhtml\ValidateConfig->verify() #2 /home/m3.lasthash.com/public_html/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/home/m3.lastha...') #3 /home/m3.lasthash.com/public_html/vendor/magento/framework/View/Element/Template.php(270): Magento\Framework\View\TemplateEngine\Php->render(Object(MagePal\GmailSmtpApp\Block\Adminhtml\ValidateConfig), '/home/m3.lastha...', Array) #4 /home/m3.lasthash.com/public_html/vendor/magento/framework/View/Element/Template.php(300): Magen in /home/m3.lasthash.com/public_html/app/code/MagePal/GmailSmtpApp/Block/Adminhtml/ValidateConfig.php on line 288

**Comment by nomadicshiv** [comment]
Error on de compile

Compilation was started.
Repositories code generation... 1/7 [====>-----------------------]  14% < 1 sec 64.5 MiBPHP Parse error:  syntax error, unexpected 'Data' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in /home/m3.lasthash.com/public_html/app/code/MagePal/GmailSmtpApp/Plugin/Mail/TransportPlugin.php on line 27

Parse error: syntax error, unexpected 'Data' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in /home/m3.lasthash.com/public_html/app/code/MagePal/GmailSmtpApp/Plugin/Mail/TransportPlugin.php on line 27

**Comment by nomadicshiv** [comment]
i am using php 7.2

**Comment by srenon** [comment]
You are using an older version of Magento which is using ZendFramework instead of Laminas.

Please install using composer or version https://github.com/magepal/magento2-gmail-smtp-app/releases/tag/2.8.7

**Comment by nomadicshiv** [comment]
thanks its working fine
