### ISSUE TITLE
Magento 2.4.5 compatibility

### ISSUE THREAD

**Issue by simonmaass** [magepal/magento2-gmail-smtp-app#187]
Is this module compatible with m2.4.5? and php 8.1?

**Comment by srenon** [comment]
@simonmaass .. are you having issues?

**Comment by simonmaass** [comment]
@srenon starting the upgrade process... was just wondering in advance... will keep you updated...

**Comment by srenon** [comment]
See https://github.com/magepal/magento2-gmail-smtp-app/blob/master/composer.json#L19
