### ISSUE TITLE
2.4.6 Class Issue

### ISSUE THREAD

**Issue by saderra** [magepal/magento2-gmail-smtp-app#191]
#### Preconditions

Just upgraded to 2.4.6 and received this error when attempting to compile: 

There is an error in /var/www/mage/vendor/magepal/magento2-gmailsmtpapp/Model/Transport.php at line: 19
Class "Zend_Mail_Transport_Sendmail" not found#0 /var/www/mage/vendor/composer/ClassLoader.php(582): include()
#1 /var/www/mage/vendor/composer/ClassLoader.php(433): Composer\Autoload\{closure}()
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#3 /var/www/mage/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(134): class_exists()
#4 /var/www/mage/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(117): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->includeClass()
#5 /var/www/mage/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(87): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->extract()
#6 /var/www/mage/setup/src/Magento/Setup/Module/Di/App/Task/Operation/RepositoryGenerator.php(61): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->getList()
#7 /var/www/mage/setup/src/Magento/Setup/Module/Di/App/Task/Manager.php(56): Magento\Setup\Module\Di\App\Task\Operation\RepositoryGenerator->doOperation()
#8 /var/www/mage/setup/src/Magento/Setup/Console/Command/DiCompileCommand.php(216): Magento\Setup\Module\Di\App\Task\Manager->process()
#9 /var/www/mage/vendor/symfony/console/Command/Command.php(298): Magento\Setup\Console\Command\DiCompileCommand->execute()
#10 /var/www/mage/vendor/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#11 /var/www/mage/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#12 /var/www/mage/vendor/magento/framework/Console/Cli.php(116): Symfony\Component\Console\Application->doRun()
#13 /var/www/mage/vendor/symfony/console/Application.php(171): Magento\Framework\Console\Cli->doRun()
#14 /var/www/mage/bin/magento(23): Symfony\Component\Console\Application->run()
#15 {main}

**Comment by srenon** [comment]
@saderra - Please upgrade to 2.9.1
