### ISSUE TITLE
Test Mail Works through extension but magento 2 is not sending any emails

### ISSUE THREAD

**Issue by grvsooryen** [magepal/magento2-gmail-smtp-app#71]
We have configured all settings but email is not going from magento 2 module, but test mail from this extension is going.
![mailsettings](https://user-images.githubusercontent.com/16348876/28163875-7c510754-67ea-11e7-83d8-b416c88c7fd7.png)

**Comment by srenon** [comment]
@grvsooryen  are you still having an issue?

**Comment by Nik3las** [comment]
Having the same problem, test mail sends on an address but when trying to save configuration it won't save the password. Result after saving a password "5.7.8 Username and Password not accepted. Learn more at 5.7.8 https://support.google.com/mail/?p=BadCredentials 90sm4591830wrk.38 - gsmtp" Allow less secure apps: (is turned) ON

Any insight? It is turning me insane trying to configure this.

**Comment by srenon** [comment]
@Nik3las ...What do you mean by "won't save the password."?

Is this multi-store?

**Comment by Nik3las** [comment]
In Stores > Configuration > System > Gmail/Google Apps SMTP Pro When I enter the host, port, username, password etc. and click Save Config, after that when I try to Send Test Email I got this result 

> "5.7.8 Username and Password not accepted. Learn more at 5.7.8 https://support.google.com/mail/?p=BadCredentials 90sm4591830wrk.38 - gsmtp" 

I am running Magento 2.1.7
Thank you for your answer @srenon

**Comment by grvsooryen** [comment]
Yes, I still have problem.

**Comment by tommybds** [comment]
Have the probleme too on a magento 2 multistore 2.1.7 with zoho smtp and ssl setting

**Comment by Nik3las** [comment]
@grvsooryen @tommybds did you try changing the **Store View** ?

**Comment by tommybds** [comment]
@Nik3las yes tried on website and store views, same result, authentification failed because of password not saved by what I see

**Comment by dev-Dhaval** [comment]
have you got any solution ?
test email is working fine but magento email is not working

**Comment by richgal** [comment]
I got the same problem. test works fine but non of the emails are sent out.

**Comment by sunilit42** [comment]
@richgal  @dev-Dhaval 

any solution for that?

**Comment by srenon** [comment]
@sunilit42 ... can you provide more information on your setup (single/multi-store, version, any other email like extension etc)

Debug and check if this line is getting executed https://github.com/magepal/magento2-gmailsmtpapp/blob/master/Model/Transport.php#L24

**Comment by srenon** [comment]
@sunilit42 ... can you provide a list of all third-party modules

     php bin/magento module:status | grep -v Magento

**Comment by Kayhen** [comment]
I am having the same issue "Test Mail Works through extension but Magento 2 is not sending any emails" has anyone solved it?

Currently I have tow third party modules List of enabled modules:
 - Hiddentechies_Bizkick
 - MagePal_GmailSmtpApp

**Comment by srenon** [comment]
Is "Disable Email Communications" set to "Yes" or "No"?

![image](https://user-images.githubusercontent.com/1415141/32442594-fb5a79a6-c2c9-11e7-8a86-09bf45bff84d.png)

**Comment by Fitdiva** [comment]
https://github.com/magento/magento2/issues/6146

**Comment by manuelson** [comment]
Same issue

**Comment by srenon** [comment]
@maderlock ... Is "Disable Email Communications" set to "Yes" or "No"?

**Comment by faherne** [comment]
The issue you're having is related to Gmail's high security requirements for email clients - Google pretty much only trust their own apps/browser. Try connect with Outlook to your Gmail/GSuite email account via POP/IMAP. You'll get the same error. You need to enable insecure email client access in your Gmail/GSuite settings. It's very convoluted.

**Comment by manuelson** [comment]
@srenon is set to "No"

**Comment by Vinicius-Teles** [comment]
I have the same error. My e-mail test working, mas any other e-mail not working

**Comment by swiac** [comment]
Had the same issue on Magento 2.2.1 and 2.2.2 whereby test emails worked but transaction emails did not. Everything was set up correctly on v1.4.5 and tried with Gmail and SendGrid.

Upgraded to v1.5.1 and transaction emails worked correctly!

**Comment by swordsreversed** [comment]
@srenon should "Disable Email Communications" be set to "Yes" or "No"? I can't send any email at the moment.

**Comment by srenon** [comment]
@swordsreversed .... Yes you can disable it in MagePal Smtp setting.

Could you provide me a list of OS, M2 version, and list of all custom module installed?

**Comment by stone-ly** [comment]
Same here, sending test mail goes fine but won't save password correctly.
5.7.8 Error: authentication failed: UGFzc3dvcmQ6
Magento 2.2.2 with single store single view, Ubuntu 16.04
Appreciated your time and help.

**Comment by stone-ly** [comment]
Hello guys, finally I figured that out! After saving the credentials go to cache and flush cache storage instead of flush cache. Hopefully can help someone in the same situation.
Thanks go to developer for such a great extension!

**Comment by srenon** [comment]
@stone-ly ... thanks for the update. 

I'm thinking about adding another test button that will send email using Magento setting (So you will be able to test both server config and Magento config

**Comment by srenon** [comment]
Please install version 2.5.0 and let me know if it provides more information on what causing your issues

**Comment by srenon** [comment]
Please create a new issue if anyone still having problems

**Comment by lano-vargas** [comment]
@moejoee91   I think you've got a point about SSL not sure if its related but is was working for me before ssl was turned on /added to the domain and none of the email are send is it too much of a coincidence or could really be ssl related? did you find anything? thanks

**Comment by knambiar** [comment]
Magento 2 seems to use the sendmail API which isn't installed by default on a lot of Ubuntu servers at least. I ran the following command to install it and after than everything seems to work perfectly:

`$ sudo apt-get install sendmail`

**Comment by jpelayo** [comment]
Same problem for me with Magento 2.3.2 + php 7.2 . SMTP works in test mode , but I can't send an invoice, for instance. I removed sendmail to make sure it does not fall back to php mail() .

**Comment by srenon** [comment]
@jpelayo ... if you having an issue please open a new ticket. Also, all our test environment use of Magento 2.3.1 with PHP7.2.x or Magento 2.3.2 with PHP 7.1.x without any issues. So more than like your issue is caused by something in your environment.
