### ISSUE TITLE
5.7.1 : Sender address rejected: not owned by user

### ISSUE THREAD

**Issue by alen12345** [magepal/magento2-gmail-smtp-app#94]
Experiencing this issue when using the feature "Email to a friend"; the problem is that the email of the sender is different from the one of my company, and so the message is rejected.

Any additional setting to allow this feature?

**Comment by srenon** [comment]
What email provider?

What setting do you have here

![image](https://user-images.githubusercontent.com/1415141/34578274-5313346a-f152-11e7-82d4-a6b167492512.png)

**Comment by alen12345** [comment]
I have: Set Return-Path: Yes

Email provider: I am running my own mail server on a VPS using either docker-mailserver or mail-in-a-box prjects.

**Comment by srenon** [comment]
@alen12345 ... Please update to version 2.5.0, the test feature has been rewritten, so you could enter the "friend from" and "friend to" address to simulate the email to the friend feature.

I think you may need to disable the "Set From" address (set it to No)

![image](https://user-images.githubusercontent.com/1415141/36030880-e0ddd5bc-0d76-11e8-83f6-973fe21d6cbd.png)

**Comment by alen12345** [comment]
Disabled "Set From", and works perfectly in the frontend!

Issue solved, thank you @srenon !
