### ISSUE TITLE
Connection timed out - When I try to send the test email

### ISSUE THREAD

**Issue by francoeder** [magepal/magento2-gmail-smtp-app#97]
Hi! When i try to send the test email, the message "Connection timed out" is returned.

![email test - connection timed out](https://user-images.githubusercontent.com/13442629/35472650-46abd654-035a-11e8-9458-22dbb17b8b18.png)

My application is on a DigitalOcean VPS, Linux Ubuntu.
Tell me what information i need to give you, to help you to help me.
I really appreciate your attention! Thank you!

**Comment by srenon** [comment]
Take a look at https://github.com/magepal/magento2-gmail-smtp-app/issues/96 and https://github.com/magepal/magento2-gmail-smtp-app/issues/12

From your server terminal, what does this return?
>php -r "mail('s@gmail.com', 'My Subject', 'test');"
