### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by Sipestian** [magepal/magento2-gmail-smtp-app#98]
Hi,

I've been trying to set-up but keeps saying Connection Refused. I have the same email on my iPhone & Outlook...

What can I do to solve this? 

Thanks in advance

**Comment by srenon** [comment]
"Connection refused" mean something is blocked.

https://github.com/magepal/magento2-gmail-smtp-app/issues/58

Also is your "reply from" email address the same as your username/password address?

**Comment by Sipestian** [comment]
Please have a look at the screenshot

https://prnt.sc/i6u0v4

**Comment by srenon** [comment]
You should check with your hosting company to see if they are blocking that port... see https://github.com/PHPMailer/PHPMailer/issues/770
